on: [push, pull_request]

name: CI

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: prepare build
        run: |
          go get github.com/mitchellh/gox
          ls -al /opt/hostedtoolcache/go/1.14.6/x64/
          sudo cp ${GOROOT}/bin/gox /usr/bin/gox
          sudo gem install fpm -v 1.11.0

      - name: checkout code
        uses: actions/checkout@v2

      - name: run tests
        run: make test

      - name: build binary
        run: make gox-build

      - name: build Docker images
        run: make image-dev
